server:
  port: 9000
spring:
  application:
    name: test-server
eureka:
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false